### ISSUE TITLE
Prepopulated CVN count incorrect for PSI CVN

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1018]
The UI user data entry dialog box presumably prepopulated the PSI CVN count as zero and suggested an override for the single occurrence of FFh in the CVN.

[PSI missed number of Cal IDs.docx](https://github.com/battjt/j1939-84/files/6593068/PSI.missed.number.of.Cal.IDs.docx)

The correct prepopulated CVN count should be 1 and there should be no override checkbox.

**Comment by gumbelmj** [comment]
As designed, the override checkbox will be presented to the user anytime the "OK" button is disabled because the vehicle information is not 'valid' (See [VehicleInformationPresenter.java](https://github.com/battjt/j1939-84/blob/b8723bad439b43d66914bdaf4a27984797f83a43/src/org/etools/j1939_84/ui/VehicleInformationPresenter.java#L333))  

In this case, the tool queried the vehicle for DM19s and, for an unknown reason, the response wasn't picked up by the tool.  Inspecting the packet logs, I believe the ECU did provide a DM19.

The information is gathered from the vehicle as a convenience to the user, with the option to override any incorrect data.  

Since there is no requirement for pre-populating the this data, I don't think the tool needs to be changed to accomodate this edge case.
