### ISSUE TITLE
J1939-84 too strict on ignition cycle count diagnostic 6.7.13.2.a

### ISSUE THREAD

**Issue by jacobbosch-cummins** [Equipment-and-Tool-Institute/j1939-84#1082]
Action 6.6.11.1.d allows for an optional engine start, which is not accounted for by Fail Criteria 6.7.13.2.a.  The J1939-84 tool implements the diagnostic as written, which causes the tool to generate an incorrect failure when engine is not started at 6.6.11.1.d.

Recommend modifying 6.7.13.2.a to allow 2 or 3 ignition cycle increments since Part 5.

**Comment by ericthomasswenson** [comment]
6.5.6 DM20: Monitor Performance Ratio 
6.5.6.1 Actions 
a. DS DM20 {(send Request (PG 59904) for PG 49664 (SP 3048)]) to OBD ECU(s) that provided DM20 data in part 1. 
b. Store each ignition cycle counter value (SP 3048) for future use.  

6.5.7 Complete Fault A Three Trip Countdown Cycle 1 and Cycle 2  
6.5.7.1 Actions 
a. Turn the engine off to complete the first cycle.  
b. Wait manufacturer’s recommended interval with the key in the off position.  
c. **_Start Engine for second cycle._**  
d. Wait for manufacturer’s recommended time for Fault A to be detected as passed.  
e. Turn the engine off to complete the second cycle.  
f. Wait manufacturer’s recommended interval with the key in the off position. 
g. **_Start the engine for part 6._**  
h. Wait for manufacturer’s recommended time for Fault A to be detected as passed.  

6.6.11.1 Actions 
a. Turn engine off. 
b. Wait engine manufacturer’s recommended interval for key on to key off transition.  
c. Turn key to on position.  
d. If required by engine manufacturer, **_start the engine for start to start operating cycle_** effects.49  
e. Otherwise, Proceed with part 7.  
f. Turn engine off.  
g. Wait engine manufacturer’s recommended interval for key on to key off transition.  
h. **_Turn the key to the on position._**  
i. Proceed with part 7.  

6.7.13.2 Fail Criteria 
a. Fail if ignition cycle counter (SP 3048) for any ECU has incremented by other than 3 cycles from part 5.

**Comment by ericthomasswenson** [comment]
Counts of 2 or 3 both appear to be correct for 6.7.13.2.

Recommended for task 8.

**Comment by ericthomasswenson** [comment]
@jacobbosch-cummins is this still a problem?

**Comment by jacobbosch-cummins** [comment]
I can confirm this issue still exists in 3.1.20.  I did not start the engine at the optional engine start described by Action 6.6.11.1.d.

Start Test 5.6 - DM20: Monitor performance ratio
11:01:12.8916 Destination Specific DM20 Request to Engine #1 (0)
11:01:12.8952 18EA00F9 [3] 00 C2 00 (TX)
11:01:12.9079 1CC2F900 [53] 0A 00 00 00 C9 14 F8 00 00 00 00 F2 0B F8 00 00 00 00 C6 14 F8 00 00 00 00 EF 0B F8 0A 00 00 00 CA 14 F8 00 00 00 00 B8 12 F8 00 00 00 00 F8 0B F8 00 00 00 00
DM20 from Engine #1 (0):  [
                                                            Num'r /  Den'r
  Ignition Cycles                                                       10
  OBD Monitoring Conditions Encountered                                  0
  SPN 5321 Engine Intake Manifold Pressure System Monitor       0 /      0
  SPN 3058 Engine EGR System Monitor                            0 /      0
  SPN 5318 AFT Exhaust Gas Sensor System Monitor                0 /      0
  SPN 3055 Engine Fuel System Monitor                          10 /      0
  SPN 5322 AFT NMHC Converting Catalyst System Monitor          0 /      0
  SPN 4792 AFT 1 SCR System                                     0 /      0
  SPN 3064 AFT DPF System Monitor                               0 /      0
]

Start Test 7.13 - DM20: Monitor performance ratio
11:03:33.9468 Destination Specific DM20 Request to Engine #1 (0)
11:03:33.9511 18EA00F9 [3] 00 C2 00 (TX)
11:03:33.9590 1CC2F900 [53] 0C 00 00 00 C9 14 F8 00 00 00 00 F2 0B F8 00 00 00 00 C6 14 F8 00 00 00 00 EF 0B F8 0C 00 00 00 CA 14 F8 00 00 00 00 B8 12 F8 00 00 00 00 F8 0B F8 00 00 00 00
DM20 from Engine #1 (0):  [
                                                            Num'r /  Den'r
  Ignition Cycles                                                       12
  OBD Monitoring Conditions Encountered                                  0
  SPN 5321 Engine Intake Manifold Pressure System Monitor       0 /      0
  SPN 3058 Engine EGR System Monitor                            0 /      0
  SPN 5318 AFT Exhaust Gas Sensor System Monitor                0 /      0
  SPN 3055 Engine Fuel System Monitor                          12 /      0
  SPN 5322 AFT NMHC Converting Catalyst System Monitor          0 /      0
  SPN 4792 AFT 1 SCR System                                     0 /      0
  SPN 3064 AFT DPF System Monitor                               0 /      0
]
FAIL: 6.7.13.2.a - Ignition cycle counter for Engine #1 (0) has incremented by other than 3 cycles from part 5

**Comment by ericthomasswenson** [comment]
And I don’t recall using the user input on the number of cycles in the criteria either.

Best Wishes,

Eric Swenson

**Comment by ericthomasswenson** [comment]
Is there a housekeeping issue…

If the 6.7 DM20 ignition cycle count is wrong … then is is likely that the three cycle countdown should fail for DM28 … the count is a quality control measure as used here.

6.7.13 DM20: Monitor Performance Ratio 
6.7.13.1 Actions 
a. DS DM20 [send Request (PGN 59904) using PGN 49664 (SPN 3048)] to ECU(s) that responded in part 5 with DM20 data. 
6.7.13.2 Fail Criteria 
a. Fail if ignition cycle counter (SPN 3048) for any ECU has incremented by other than 3 cycles from part 5.

**Comment by ericthomasswenson** [comment]
Proposed revision

6.7.13.2 Fail Criteria
a. Fail if ignition cycle counter (SP 3048) for any ECU has incremented by **_less than 2 or more than 3 cycles_** from part 5.

**Comment by ericthomasswenson** [comment]
Proposed text confirmed as correct. Thus nay be implemented prior to artifact update.

**Comment by jacobbosch-cummins** [comment]
The fix seems effective in 3.1.25.
