### ISSUE TITLE
Tool Falsely Failed SA 0 for Erased Test Results

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1088]
ETS-03-29-2022

_SA 0 was failed for **test results** in Part 9_.  This complaint may have cascaded from #1091.

**The tool falsely flags that our controller erased DM5 data.**

17:56:46.2271 Destination Specific DM5 Request to Engine #2 (1)
17:56:46.2316 18EA01F9 [3] CE FE 00 (TX)
17:56:46.2446 18FECE01 [8] 00 00 14 37 E0 02 E0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
FAIL: 6.4.13.2.a - Engine #2 (1) erased DM5 data

**DM5 from earlier in part 4:**
17:56:31.7991 18FECE01 [8] 00 00 14 37 E0 02 E0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

**Comment by ericthomasswenson** [comment]
I Suggest fixing https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1091 first, and see if the unexpected test results problem was a side-effect of unexpected data discrepancies from the TID F6 support showing the manufacturer-defined SPs and the incorrect placement of the the MSBits, shown in https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1091, leading to an interpretation of missing test results.

This reminded me of #1034, where there was a 1-bit difference, but appears to be unrelated.

**Comment by naroner** [comment]
What is needed to confirm this?

**Comment by ericthomasswenson** [comment]
**_14 37 E0 02 E0 02 Is a composite value in_**

**_in 17:56:31.7991 18FECE01 [8] 00 00 14 37 E0 02 E0 02_**

Part 2 responses are.

Start Test 2.2 - DM5: Diagnostic readiness 1

14:38:02.2833 Global DM5 Request
14:38:02.2837 18EAFFF9 [3] CE FE 00 (TX)
14:38:02.2877 18FECE3D [8] 00 00 14 04 60 1C 60 1C
DM5 from Exhaust Emission Controller (61): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
14:38:02.2884 18FECE01 [8] 00 00 14 37 A0 02 A0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
14:38:02.2926 18FECE00 [8] 00 00 14 04 00 00 00 00
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Fuel System                    supported, not complete
    Heated catalyst            not supported,     complete
    Misfire                        supported, not complete
    NMHC converting catalyst       supported, not complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

WARN: 6.2.2.2.a (A6.2.d) - Exhaust Gas Sensor is supported by more than one OBD ECU
WARN: 6.2.2.2.c - Required monitor Exhaust Gas Sensor is supported by more than one OBD ECU

14:38:02.8962 Destination Specific DM5 Request to Engine #1 (0)
14:38:02.8967 18EA00F9 [3] CE FE 00 (TX)
14:38:02.9019 18FECE00 [8] 00 00 14 04 00 00 00 00
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

14:38:02.9038 Destination Specific DM5 Request to Engine #2 (1)
14:38:02.9056 18EA01F9 [3] CE FE 00 (TX)
14:38:02.9191 18FECE01 [8] 00 00 14 37 A0 02 A0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

14:38:02.9200 Destination Specific DM5 Request to Exhaust Emission Controller (61)
14:38:02.9213 18EA3DF9 [3] CE FE 00 (TX)
14:38:02.9277 18FECE3D [8] 00 00 14 04 60 1C 60 1C
DM5 from Exhaust Emission Controller (61): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

End Test 2.2 - DM5: Diagnostic readiness 1

**Comment by ericthomasswenson** [comment]
In Part 9, SA 0 fails, attributed to test data, and not DM5.
I think it is clear that SA 0 should have passed.

SA 0 Having no test data, or #1091, the manufacturer assigned SPs problem, each may explain the observed performance.  SA 0 had one positive response, for DM5, which did not change from Part 2.

15:26:23.8949 Global DM22 Request
15:26:23.8962 18C3FFF9 [8] 01 FF FF FF FF FF FF FF (TX)
15:26:24.4948 Timeout - No Response

15:26:24.4993 Global DM22 Request
15:26:24.5017 18C3FFF9 [8] 11 FF FF FF FF FF FF FF (TX)
15:26:25.0993 Timeout - No Response

6.9.3.10.d - Checking for erased diagnostic information

15:26:25.1048 Destination Specific DM6 Request to Engine #1 (0)
15:26:25.1054 18EA00F9 [3] CF FE 00 (TX)
15:26:25.1111 18E8FF00 [8] 01 FF FF FF F9 CF FE 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65231

15:26:25.1123 Destination Specific DM12 Request to Engine #1 (0)
15:26:25.1143 18EA00F9 [3] D4 FE 00 (TX)
15:26:25.1208 18E8FF00 [8] 01 FF FF FF F9 D4 FE 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65236

15:26:25.1212 Destination Specific DM23 Request to Engine #1 (0)
15:26:25.1234 18EA00F9 [3] B5 FD 00 (TX)
15:26:25.1307 18E8FF00 [8] 01 FF FF FF F9 B5 FD 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64949

15:26:25.1311 Destination Specific DM29 Request to Engine #1 (0)
15:26:25.1326 18EA00F9 [3] 00 9E 00 (TX)
15:26:25.1407 18E8FF00 [8] 01 FF FF FF F9 00 9E 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 40448

15:26:25.1411 Destination Specific DM5 Request to Engine #1 (0)
15:26:25.1424 18EA00F9 [3] CE FE 00 (TX)
15:26:25.1507 18FECE00 [8] 00 00 14 04 00 00 00 00
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

15:26:25.1523 Destination Specific DM25 Request to Engine #1 (0)
15:26:25.1529 18EA00F9 [3] B7 FD 00 (TX)
15:26:25.1607 18E8FF00 [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951

15:26:25.1616 Destination Specific DM31 Request to Engine #1 (0)
15:26:25.1633 18EA00F9 [3] 00 A3 00 (TX)
15:26:25.1707 18E8FF00 [8] 01 FF FF FF F9 00 A3 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41728

15:26:25.1709 Destination Specific DM21 Request to Engine #1 (0)
15:26:25.1728 18EA00F9 [3] 00 C1 00 (TX)
15:26:25.1807 18E8FF00 [8] 01 FF FF FF F9 00 C1 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 49408

15:26:25.1817 Destination Specific DM26 Request to Engine #1 (0)
15:26:25.1829 18EA00F9 [3] B8 FD 00 (TX)
15:26:25.1904 18E8FF00 [8] 01 FF FF FF F9 B8 FD 00
Acknowledgment from Engine #1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64952
**_FAIL: 6.9.3.10.d - Engine #1 (0) erased Test Results data_**

**Comment by ericthomasswenson** [comment]
**_It appears Engine #1 SA 1 passes._**

15:26:25.1919 Destination Specific DM6 Request to Engine #2 (1)
15:26:25.1933 18EA01F9 [3] CF FE 00 (TX)
15:26:25.2123 18FECF01 [8] 43 FF 00 00 00 00 FF FF
DM6 from Engine #2 (1): MIL: on, RSL: off, AWL: off, PL: not supported, No DTCs

15:26:25.2129 Destination Specific DM12 Request to Engine #2 (1)
15:26:25.2148 18EA01F9 [3] D4 FE 00 (TX)
15:26:25.2189 18FED401 [8] 43 FF 9B 01 04 01 FF FF
DM12 from Engine #2 (1): MIL: on, RSL: off, AWL: off, PL: not supported
DTC 411:4 - Engine EGR 1 Differential Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

15:26:25.2201 Destination Specific DM23 Request to Engine #2 (1)
15:26:25.2214 18EA01F9 [3] B5 FD 00 (TX)
15:26:25.2324 18FDB501 [8] 43 FF 44 15 01 01 FF FF
DM23 from Engine #2 (1): MIL: on, RSL: off, AWL: off, PL: not supported
DTC 5444:1 - Engine Crankcase Breather Oil Separator Speed, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times

15:26:25.2333 Destination Specific DM29 Request to Engine #2 (1)
15:26:25.2349 18EA01F9 [3] 00 9E 00 (TX)
15:26:25.2389 189EF901 [8] 00 FF 01 01 01 FF FF FF
DM29 from Engine #2 (1): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                1
Emission-Related Previously MIL-On DTC Count                     1
Emission-Related Permanent DTC Count                             1

15:26:25.2398 Destination Specific DM5 Request to Engine #2 (1)
15:26:25.2414 18EA01F9 [3] CE FE 00 (TX)
15:26:25.2507 18FECE01 [8] 01 01 14 37 A0 02 A0 02
DM5 from Engine #2 (1): OBD Compliance: HD OBD (20), Active Codes: 1, Previously Active Codes: 1

15:26:25.2509 Destination Specific DM25 Request to Engine #2 (1)
15:26:25.2529 18EA01F9 [3] B7 FD 00 (TX)
15:26:25.6603 18FDB701 [136] 87 44 15 01 01 F8 9B 00 00 42 0F 9F 00 0A C8 26 52 3C C6 72 89 3D 1A 01 80 23 9E 2B B0 00 00 16 BA 30 8A 8A 80 3B 60 1F C0 28 20 32 C5 AF E1 E2 D0 FB 09 1F 6C 24 44 60 44 60 44 60 44 60 44 60 44 60 44 60 6B 27 F9 47 42 08 24 FF 34 9C 34 A5 38 3B 3A A3 39 65 00 65 00 C1 07 3C 1E 00 0E 00 00 00 00 01 0D E0 04 00 7C D9 37 34 07 A5 38 A3 39 17 04 C0 3D C0 3D 01 FF FE 00 0E 02 EC 79 04 FF FF 1A 00 BE 05 42 05
DM25 from Engine #2 (1): 
Freeze Frames: [
  Freeze Frame: {
    DTC 5444:1 - Engine Crankcase Breather Oil Separator Speed, Data Valid But Below Normal Operational Range - Most Severe Level - 1 times
    SPN Data: F8 9B 00 00 42 0F 9F 00 0A C8 26 52 3C C6 72 89 3D 1A 01 80 23 9E 2B B0 00 00 16 BA 30 8A 8A 80 3B 60 1F C0 28 20 32 C5 AF E1 E2 D0 FB 09 1F 6C 24 44 60 44 60 44 60 44 60 44 60 44 60 44 60 6B 27 F9 47 42 08 24 FF 34 9C 34 A5 38 3B 3A A3 39 65 00 65 00 C1 07 3C 1E 00 0E 00 00 00 00 01 0D E0 04 00 7C D9 37 34 07 A5 38 A3 39 17 04 C0 3D C0 3D 01 FF FE 00 0E 02 EC 79 04 FF FF 1A 00 BE 05 42 05
  }
]

15:26:25.6639 Destination Specific DM31 Request to Engine #2 (1)
15:26:25.6654 18EA01F9 [3] 00 A3 00 (TX)
15:26:25.6824 18E8FF01 [8] 01 FF FF FF F9 00 A3 00
Acknowledgment from Engine #2 (1): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41728

15:26:25.6834 Destination Specific DM21 Request to Engine #2 (1)
15:26:25.6843 18EA01F9 [3] 00 C1 00 (TX)
15:26:25.6903 18C1F901 [8] 00 00 00 00 04 00 15 00
DM21 from Engine #2 (1): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    4 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      21 minutes
]

15:26:25.6922 Destination Specific DM26 Request to Engine #2 (1)
15:26:25.6938 18EA01F9 [3] B8 FD 00 (TX)
15:26:25.6987 18FDB801 [8] 00 00 00 37 A0 02 A0 02
DM26 from Engine #2 (1): Warm-ups: 0, Time Since Engine Start: 0 seconds

15:26:25.6996 Sending DM7 for DM30 to Engine #2 (1) for SPN 157
15:26:25.7017 18E301F9 [8] F7 9D 00 1F FF FF FF FF (TX)
15:26:25.7622 18A4F901 [12] F7 9D 00 0A 5E 01 B8 7D A4 88 5C 71
DM30 from 1: SPN 157 FMI 10 (SLOT 350) Result: Test Passed. Min: -149, Value: 9.2, Max: 149 l/h

15:26:25.7651 Destination Specific DM20 Request to Engine #2 (1)
15:26:25.7664 18EA01F9 [3] 00 C2 00 (TX)
15:26:25.8819 18C2F901 [32] 0A 00 01 00 C6 14 F8 00 00 01 00 F2 0B F8 00 00 01 00 C9 14 F8 00 00 01 00 EF 0B F8 00 00 01 00
DM20 from Engine #2 (1):  [
                                                            Num'r /  Den'r
  Ignition Cycles                                                       10
  OBD Monitoring Conditions Encountered                                  1
  SPN 5318 AFT Exhaust Gas Sensor System Monitor                0 /      1
  SPN 3058 Engine EGR System Monitor                            0 /      1
  SPN 5321 Engine Intake Manifold Pressure System Monitor       0 /      1
  SPN 3055 Engine Fuel System Monitor                           0 /      1
]

15:26:25.8849 Destination Specific DM28 Request to Engine #2 (1)
15:26:25.8866 18EA01F9 [3] 80 FD 00 (TX)
15:26:25.8987 18FD8001 [8] 43 FF 9B 01 04 01 FF FF
DM28 from Engine #2 (1): MIL: on, RSL: off, AWL: off, PL: not supported
DTC 411:4 - Engine EGR 1 Differential Pressure, Voltage Below Normal, Or Shorted To Low Source - 1 times

15:26:25.8996 Destination Specific DM33 Request to Engine #2 (1)
15:26:25.9017 18EA01F9 [3] 00 A1 00 (TX)
15:26:25.9727 18A1F901 [18] 01 00 00 00 00 00 00 00 00 05 03 00 00 00 00 00 00 00
DM33 Emission Increasing AECD Active Time from Engine #2 (1): [
  EI-AECD Number = 1: Timer 1 = 0 minutes; Timer 2 = 0 minutes
  EI-AECD Number = 5: Timer 1 = 3 minutes; Timer 2 = 0 minutes
]

**Comment by ericthomasswenson** [comment]
**_It appears that SA 61 also passes._**

15:26:25.9751 Destination Specific DM6 Request to Exhaust Emission Controller (61)
15:26:25.9766 18EA3DF9 [3] CF FE 00 (TX)
15:26:25.9812 18FECF3D [8] 03 FF 00 00 00 00 FF FF
DM6 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

15:26:25.9822 Destination Specific DM12 Request to Exhaust Emission Controller (61)
15:26:25.9833 18EA3DF9 [3] D4 FE 00 (TX)
15:26:25.9911 18E8FF3D [8] 03 FF FF FF F9 D4 FE 00
Acknowledgment from Exhaust Emission Controller (61): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65236
15:26:26.1919 18EA3DF9 [3] D4 FE 00 (TX)
15:26:26.2016 18FED43D [8] 03 FF 00 00 00 00 FF FF
DM12 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

15:26:26.2022 Destination Specific DM23 Request to Exhaust Emission Controller (61)
15:26:26.2036 18EA3DF9 [3] B5 FD 00 (TX)
15:26:26.2157 18E8FF3D [8] 03 FF FF FF F9 B5 FD 00
Acknowledgment from Exhaust Emission Controller (61): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64949
15:26:26.4179 18EA3DF9 [3] B5 FD 00 (TX)
15:26:26.4216 18FDB53D [8] 03 FF 00 00 00 00 FF FF
DM23 from Exhaust Emission Controller (61): MIL: off, RSL: off, AWL: off, PL: not supported, No DTCs

15:26:26.4222 Destination Specific DM29 Request to Exhaust Emission Controller (61)
15:26:26.4236 18EA3DF9 [3] 00 9E 00 (TX)
15:26:26.4322 18E8FF3D [8] 03 FF FF FF F9 00 9E 00
Acknowledgment from Exhaust Emission Controller (61): Response: Busy, Group Function: 255, Address Acknowledged: 249, PGN Requested: 40448
15:26:26.6354 18EA3DF9 [3] 00 9E 00 (TX)
15:26:26.6411 189EF93D [8] 00 FF 00 00 00 FF FF FF
DM29 from Exhaust Emission Controller (61): 
Emission-Related Pending DTC Count                               0
All Pending DTC Count                                not available
Emission-Related MIL-On DTC Count                                0
Emission-Related Previously MIL-On DTC Count                     0
Emission-Related Permanent DTC Count                             0

15:26:26.6422 Destination Specific DM5 Request to Exhaust Emission Controller (61)
15:26:26.6438 18EA3DF9 [3] CE FE 00 (TX)
15:26:26.6511 18FECE3D [8] 00 00 14 04 60 1C 60 1C
DM5 from Exhaust Emission Controller (61): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

15:26:26.6522 Destination Specific DM25 Request to Exhaust Emission Controller (61)
15:26:26.6534 18EA3DF9 [3] B7 FD 00 (TX)
15:26:26.6616 18FDB73D [8] 00 00 00 00 00 FF FF FF
DM25 from Exhaust Emission Controller (61): 
Freeze Frames: [
  No Freeze Frames
]

15:26:26.6622 Destination Specific DM31 Request to Exhaust Emission Controller (61)
15:26:26.6636 18EA3DF9 [3] 00 A3 00 (TX)
15:26:26.6724 18E8FF3D [8] 01 FF FF FF F9 00 A3 00
Acknowledgment from Exhaust Emission Controller (61): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41728

15:26:26.6734 Destination Specific DM21 Request to Exhaust Emission Controller (61)
15:26:26.6744 18EA3DF9 [3] 00 C1 00 (TX)
15:26:26.6811 18C1F93D [8] 00 00 00 00 00 00 12 00
DM21 from Exhaust Emission Controller (61): [
  Distance Traveled While MIL is Activated:     0 km (0 mi)
  Time Run by Engine While MIL is Activated:    0 minutes
  Distance Since DTCs Cleared:                  0 km (0 mi)
  Time Since DTCs Cleared:                      18 minutes
]

15:26:26.6822 Destination Specific DM26 Request to Exhaust Emission Controller (61)
15:26:26.6838 18EA3DF9 [3] B8 FD 00 (TX)
15:26:26.6911 18FDB83D [8] 00 00 00 04 60 1C 60 1C
DM26 from Exhaust Emission Controller (61): Warm-ups: 0, Time Since Engine Start: 0 seconds

15:26:26.6921 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 1761
15:26:26.6939 18E33DF9 [8] F7 E1 06 1F FF FF FF FF (TX)
15:26:26.7311 18A4F93D [12] F7 E1 06 12 1E 00 18 9C FF FF B8 0B
DM30 from 61: SPN 1761 FMI 18 (SLOT 30) Result: Test Passed. Min: 7.5, Value: 99.9, Max: N/A %

15:26:26.7331 Destination Specific DM20 Request to Exhaust Emission Controller (61)
15:26:26.7344 18EA3DF9 [3] 00 C2 00 (TX)
15:26:26.7908 18C2F93D [32] 0A 00 01 00 CA 14 F8 00 00 00 00 B8 12 F8 00 00 01 00 C6 14 F8 00 00 01 00 F8 0B F8 00 00 01 00
DM20 from Exhaust Emission Controller (61):  [
                                                         Num'r /  Den'r
  Ignition Cycles                                                    10
  OBD Monitoring Conditions Encountered                               1
  SPN 5322 AFT NMHC Converting Catalyst System Monitor       0 /      0
  SPN 4792 AFT 1 SCR System                                  0 /      1
  SPN 5318 AFT Exhaust Gas Sensor System Monitor             0 /      1
  SPN 3064 AFT DPF System Monitor                            0 /      1
]

End Test 9.3 - DM22: Individual clear/reset of active and previously active DTC

**Comment by naroner** [comment]
> I Suggest fixing #1091 first, and see if the unexpected test results problem was a side-effect of unexpected data discrepancies from the TID F6 support showing the manufacturer-defined SPs and the incorrect placement of the the MSBits, shown in #1091, leading to an interpretation of missing test results.
> 
> This reminded me of #1034, where there was a 1-bit difference, but appears to be unrelated.

I don't think #1091 applies in this case, we don't support any test results with SA 0x00. What is the logic behind how the tool checks for deleted data?

**Comment by naroner** [comment]
This failure was for SA 1, not SA 0. #1087 is related to SA 0

**Comment by ericthomasswenson** [comment]
NR to confirm pass fail after #1091 is fixed.

**Comment by ericthomasswenson** [comment]
With the correction of #1091, these outcomes were isolated from the the assumption that unexpected test results may explain them.

The strategy to check the ECUs of a distributed system individually is logically correct.

The configuration of SA 0 is somewhat unusual and may be contributing to the outcome.  It’s NACKs are consistent with Part 1 performance.

**Comment by ericthomasswenson** [comment]
From Nathan Roner

This is still an issue even after https://github.com/Equipment-and-Tool-Institute/j1939-84/issues/1091 is fixed:

6.4.13.2.a - Checking for erased diagnostic information
11:56:17.2865 Destination Specific DM6 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.2885 18EA00F9 [3] CF FE 00 (TX)
11:56:17.2930 18E8FF00 [8] 01 FF FF FF F9 CF FE 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65231
11:56:17.2955 Destination Specific DM12 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.2980 18EA00F9 [3] D4 FE 00 (TX)
11:56:17.3030 18E8FF00 [8] 01 FF FF FF F9 D4 FE 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 65236
11:56:17.3045 Destination Specific DM23 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3080 18EA00F9 [3] B5 FD 00 (TX)
11:56:17.3135 18E8FF00 [8] 01 FF FF FF F9 B5 FD 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64949
11:56:17.3145 Destination Specific DM29 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3170 18EA00F9 [3] 00 9E 00 (TX)
11:56:17.3225 18E8FF00 [8] 01 FF FF FF F9 00 9E 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 40448
11:56:17.3245 Destination Specific DM5 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3270 18EA00F9 [3] CE FE 00 (TX)
11:56:17.3330 18FECE00 [8] [00 00 14 04 00 00 00](tel:00 00 14 04 00 00 00) 00
DM5 from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
Comprehensive component supported, complete
Fuel System not supported, complete
Misfire not supported, complete
Non-continuously Monitored System Support/Status:
A/C system refrigerant not supported, complete
Boost pressure control sys not supported, complete
Catalyst not supported, complete
Cold start aid system not supported, complete
Diesel Particulate Filter not supported, complete
EGR/VVT system not supported, complete
Evaporative system not supported, complete
Exhaust Gas Sensor not supported, complete
Exhaust Gas Sensor heater not supported, complete
Heated catalyst not supported, complete
NMHC converting catalyst not supported, complete
NOx catalyst/adsorber not supported, complete
Secondary air system not supported, complete
11:56:17.3385 Destination Specific DM25 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3410 18EA00F9 [3] B7 FD 00 (TX)
11:56:17.3435 18E8FF00 [8] 01 FF FF FF F9 B7 FD 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64951
11:56:17.3445 Destination Specific DM31 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3480 18EA00F9 [3] 00 A3 00 (TX)
11:56:17.3530 18E8FF00 [8] 01 FF FF FF F9 00 A3 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 41728
11:56:17.3555 Destination Specific DM21 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3590 18EA00F9 [3] 00 C1 00 (TX)
11:56:17.3635 18E8FF00 [8] 01 FF FF FF F9 00 C1 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 49408
11:56:17.3655 Destination Specific DM26 Request to Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0)
11:56:17.3690 18EA00F9 [3] B8 FD 00 (TX)
11:56:17.3735 18E8FF00 [8] 01 FF FF FF F9 B8 FD 00
Acknowledgment from Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0): Response: NACK, Group Function: 255, Address Acknowledged: 249, PGN Requested: 64952
FAIL: 6.4.13.2.a - Engine https://github.com/Equipment-and-Tool-Institute/j1939-84/pull/1 (0) erased Test Results data

**Comment by ericthomasswenson** [comment]
Eric to review with Nathan using a 3.1.3 report 7/8

**Comment by ericthomasswenson** [comment]
A comprehensive deletion criteria performance review in needed.

**Comment by battjt** [comment]
Review versus #1130. And #1039

**Comment by ericthomasswenson** [comment]
Nathan, is this still an issue?

How about we refresh using data from 3.1.14 if it is?

Above I observed.

11:56:17.3245 Destination Specific DM5 Request to Engine
11:56:17.3270 18EA00F9 [3] CE FE 00 (TX)
11:56:17.3330 18FECE00 [8] 00 00 14 04 00 00 00 00
DM5 from Engine OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

vs. 

The tool falsely flags that our controller erased DM5 data.

17:56:46.2271 Destination Specific DM5 Request to Engine 
17:56:46.2316 18EA01F9 [3] CE FE 00 (TX)
17:56:46.2446 18FECE01 [8] 00 00 14 37 E0 02 E0 02
DM5 from Engine OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
FAIL: 6.4.13.2.a - Engine (1) erased DM5 data

DM5 from earlier in part 4:
17:56:31.7991 18FECE01 [8] 00 00 14 37 E0 02 E0 02
DM5 from Engine (1): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0

**Comment by ericthomasswenson** [comment]
@naroner will check with 3.1.15 week of 3/20

**Comment by naroner** [comment]
@ericthomasswenson This is fixed in 3.1.19
