### ISSUE TITLE
Verify SP 1127 units are gauge 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1148]
Data was absolute below.  Plausibility limit is gauge.

PGN 65190 with Supported SPNs 
13:27:45.8954 18FEA600 [8] 12 03 FF FF FF FF FF FF
Found: Intake Manifold Information 1 from Engine #1 (0): 
  SPN  1127, Engine Turbocharger 1 Boost Pressure: 98.250 kPa
  SPN  1128, Engine Turbocharger 2 Boost Pressure: Not Available
  SPN  1129, Engine Turbocharger 3 Boost Pressure: Not Available
  SPN  1130, Engine Turbocharger 4 Boost Pressure: Not Available

WARN: 6.1.26.2.c - N.8 Engine #1 (0) reported value for SPN 1127 (98.25) is implausible
WARN: 6.1.26.4.a - N.7 Provided SPN 1127 is not indicated as supported by Engine #1 (0)

**Comment by PVEcompliance** [comment]
The -84 tool and by extension Table A-1 are correct.  SPN 1127 is to be sent as gauge/relative and not as absolute as seen in this sample.

Bob Halfman
Navistar, Inc.


From: ericthomasswenson ***@***.***>
Sent: Thursday, June 2, 2022 8:44 PM
To: Equipment-and-Tool-Institute/j1939-84 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Equipment-and-Tool-Institute/j1939-84] Verify SP 1127 units are gauge (Issue #1148)

[EXTERNAL EMAIL - If you suspect the validity of this email, do not click any links and use the Report Phish button to report it. If you do not see the Report Phish button, immediately forward it to ***@***.***

Data was absolute below.

PGN 65190 with Supported SPNs
13:27:45.8954 18FEA600 [8] 12 03 FF FF FF FF FF FF
Found: Intake Manifold Information 1 from Engine #1<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEquipment-and-Tool-Institute%2Fj1939-84%2Fpull%2F1&data=05%7C01%7CBob.Halfman%40Navistar.com%7C271c32d01b6d45a636ec08da45029a1e%7Cb5a920d67d3c44febaad4ffed6b8774d%7C0%7C0%7C637898174720694414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TIiEbPXamW6mejwmavpSzYETki%2F6NJgp7i1eBprXWj8%3D&reserved=0> (0):
SPN 1127, Engine Turbocharger 1 Boost Pressure: 98.250 kPa
SPN 1128, Engine Turbocharger 2 Boost Pressure: Not Available
SPN 1129, Engine Turbocharger 3 Boost Pressure: Not Available
SPN 1130, Engine Turbocharger 4 Boost Pressure: Not Available

WARN: 6.1.26.2.c - N.8 Engine #1<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEquipment-and-Tool-Institute%2Fj1939-84%2Fpull%2F1&data=05%7C01%7CBob.Halfman%40Navistar.com%7C271c32d01b6d45a636ec08da45029a1e%7Cb5a920d67d3c44febaad4ffed6b8774d%7C0%7C0%7C637898174720694414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TIiEbPXamW6mejwmavpSzYETki%2F6NJgp7i1eBprXWj8%3D&reserved=0> (0) reported value for SPN 1127 (98.25) is implausible
WARN: 6.1.26.4.a - N.7 Provided SPN 1127 is not indicated as supported by Engine #1<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEquipment-and-Tool-Institute%2Fj1939-84%2Fpull%2F1&data=05%7C01%7CBob.Halfman%40Navistar.com%7C271c32d01b6d45a636ec08da45029a1e%7Cb5a920d67d3c44febaad4ffed6b8774d%7C0%7C0%7C637898174720694414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TIiEbPXamW6mejwmavpSzYETki%2F6NJgp7i1eBprXWj8%3D&reserved=0> (0)

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEquipment-and-Tool-Institute%2Fj1939-84%2Fissues%2F1148&data=05%7C01%7CBob.Halfman%40Navistar.com%7C271c32d01b6d45a636ec08da45029a1e%7Cb5a920d67d3c44febaad4ffed6b8774d%7C0%7C0%7C637898174720694414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LAdSMQ6JLxCpqQbwLdnePx27%2F9CWzA97Nd6%2BX3g61SE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALQEVRCET5YCX4RTR4TMIGTVNFPPVANCNFSM5XW6LPDQ&data=05%7C01%7CBob.Halfman%40Navistar.com%7C271c32d01b6d45a636ec08da45029a1e%7Cb5a920d67d3c44febaad4ffed6b8774d%7C0%7C0%7C637898174720694414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xm7r6WLJObqiFFUWCJfnFtR6PSh3O5qEQ06ICbAtn%2Fs%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________

Disclaimer Confidentiality Notice: This e-mail, and any attachments
and/or documents linked to this email, are intended for the
addressee and may contain information that is privileged,
confidential, proprietary, or otherwise protected by law. Any
dissemination, distribution, or copying is prohibited. This
notice serves as a confidentiality marking for the purpose of
any confidentiality or nondisclosure agreement. If you have
received this communication in error, please contact the
original sender.

**Comment by ericthomasswenson** [comment]
The gauge plausibility valve limit is hereby confirmed.
