### ISSUE TITLE
Change the units displayed for Engine Run Time from _**s**_ to min in GHG Tracking displays

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#1238]
Change the units displayed for Engine Run Time from _**s**_ to min in GHG Tracking displays.
There are 3 locations in 6.1.26, 6.2.17, and 6.11.13.
Minutes are clearly displayed.

10:16:46.1617 GHG Tracking Arrays from Engine #1 (0)
|-------------------------+-------------+-------------+-------------|
|                         |    Active   |    Stored   |             |
|                         |   100 Hour  |   100 Hour  |   Lifetime  |
|-------------------------+-------------+-------------+-------------|
| Engine Run Time, **_s_**      |           0 |           0 |          14 |
| Vehicle Dist., km       |           0 |           0 |           0 |
| …
| Stop-Start Run Time, s  |         N/A |         N/A |         N/A |
|-------------------------+-------------+-------------+-------------|
// Minutes appear to be displayed… change s to min. only on the indicated line

**Comment by battjt** [comment]
Looking at the code, it appears that all rows are displaying minute values instead of second values.  When converting the SPN value to text, any value with a unit of 's' is converted to minutes and any unit of 'm' is converted from meters to km.
```
        String unit = spn.getSlot().getUnit();
        if ("s".equals(unit)) {
            value = value / 60; //Convert seconds to minutes
        } else if ("m".equals(unit)) {
            value = value / 1000; //Convert meters to kilometers
        }
```
Should we also change "Urban Speed Run Time", "Idle Run Time", "PTO Run Time", and "Stop-Start Run Time" to be labeled as "seconds" or make them display "minute" values?

**Comment by ericthomasswenson** [comment]
Where the data in the tabular display is in minutes, let’s make the units label say minutes …
Minutes was used to minimize line wrap 

Best Wishes,

Eric Swenson
