### ISSUE TITLE
During Erased Data Check the Tool Issues a Failure for "Erased Test Results Data"

### ISSUE THREAD

**Issue by naroner** [Equipment-and-Tool-Institute/j1939-84#1273]
**In 3.1.23 the tool has started to issue a failure for "Erased Test Results Data" during every check for deleted information.**

**Based on the DM7 request for SPN 5846 in the proceeding part of the test it appears that the tool is failing to request all the supported SPNs** 

**DM7 Request for SPN 5846 in the immediately proceeding part of the test**
12:46:09.9164 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 5846
DM30 from Exhaust Emission Controller (61): [
  SPN 1761 FMI 18 (SLOT 30) Result: Test Passed. Min: 7.5, Value: 87.37, Max: N/A %
  SPN 3056 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3057 FMI 2 (SLOT 32) Result: Test Not Complete.
  SPN 3216 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 3216 FMI 20 (SLOT 295) Result: Test Not Complete.
  SPN 3216 FMI 21 (SLOT 295) Result: Test Not Complete.
  _... Removed for clarity_

**Checking for deleted data step, SPN 1761 and 3056 are not requested**
12:46:24.2364 Destination Specific DM26 Request to Exhaust Emission Controller (61)
12:46:24.2409 18EA3DF9 [3] B8 FD 00 (TX)
12:46:24.2524 18FDB83D [8] 00 00 06 04 60 1C 60 1C
 _... Removed for clarity_

12:46:24.2524 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 3226
12:46:24.2559 18E33DF9 [8] F7 9A 0C 1F FF FF FF FF (TX)
12:46:24.3219 1CA4F93D [36] F7 9A 0C 15 EC 00 00 FB FF FF FF FF F7 9A 0C 14 EC 00 00 FB FF FF FF FF F7 9A 0C 0A 0C 00 00 FB FF FF FF FF
DM30 from Exhaust Emission Controller (61): [
  SPN 3226 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 3226 FMI 20 (SLOT 236) Result: Test Not Complete.
  SPN 3226 FMI 21 (SLOT 236) Result: Test Not Complete.
]

12:46:24.3239 Sending DM7 for DM30 to Exhaust Emission Controller (61) for SPN 3226
12:46:24.3264 18E33DF9 [8] F7 9A 0C 1F FF FF FF FF (TX)
12:46:24.3919 1CA4F93D [36] F7 9A 0C 15 EC 00 00 FB FF FF FF FF F7 9A 0C 14 EC 00 00 FB FF FF FF FF F7 9A 0C 0A 0C 00 00 FB FF FF FF FF
DM30 from Exhaust Emission Controller (61): [
  SPN 3226 FMI 10 (SLOT 12) Result: Test Not Complete.
  SPN 3226 FMI 20 (SLOT 236) Result: Test Not Complete.
  SPN 3226 FMI 21 (SLOT 236) Result: Test Not Complete.
]

**Controller's DM24 from part 1 for reference:**
DM24 from Exhaust Emission Controller (61): 
   _... Removed for clarity_
    F T   1  SPN 1761 - AFT 1 DEF Tank Volume
    F     1  SPN 2623 - Accelerator Pedal #1 Channel 2
    F     1  SPN 2624 - Accelerator Pedal #1 Channel 3
    F     2  SPN 2630 - Engine Charge Air Cooler 1 Outlet Temperature
    F     2  SPN 2791 - Engine EGR 1 Valve 1 Control 1
    F     1  SPN 3031 - AFT 1 DEF Tank Temperature 1
      T   0  SPN 3056 - Engine Exhaust Bank 1 O2 Sensor Monitor
      T   0  SPN 3057 - Engine Exhaust Bank 2 O2 Sensor Monitor
D   T   2  SPN 3216 - Engine Exhaust 1 NOx 1
_... Removed for clarity_

**Comment by ericthomasswenson** [comment]
@naroner please send the logs to joe@soliddesign.net

**Comment by battjt** [comment]
The report without the CAN log will be fine.

**Comment by naroner** [comment]
Log file has been provided.

**Comment by battjt** [comment]
This bug report is for 6.7.15 and 6.7.16.  It appears that the logic in 
>excluding those tests identified in 6.7.15.1.c which did not run before the DM3 was presented to the OBD ECUs.
was incorrectly simplified from English to the code (there are a lot of negatives in there and implied in the supporting data).

Incorrectly, instead of verifying the non-initialized tests from 6.1.12, the tool only verified the initialized tests.  **The implementation of #1039 and #1130 was incorrect.**

Because this was confusing, I am restating here for verification:
* initialized means 
```
        boolean initHigh = getTestValue() == 0xFB00 && getTestMinimum() == 0xFFFF && getTestMaximum() == 0xFFFF;
        boolean initLow = getTestValue() == 0x0000 && getTestMinimum() == 0x0000 && getTestMaximum() == 0x0000;
        return initHigh || initLow;
```
* run, complete, non-initialized, and not initialized all mean the inverse of _initialized_.
* In 6.7.16.2.a this
> Fail if any OBD ECU erases [test results] excluding those tests identified in 6.7.15.1.c which did not run...
meaning

Which I simplified
* Fail if any OBD ECU erases test results excluding those tests identified in 6.7.15.1.c which were _initialized_...
* Fail if any OBD ECU erases test results _including_ those tests which were _not initialized_

There are 4 lists maintained to describe different test results for each OBD module:
1. _scale test results_ as found in 6.1.12
2. _initialized_1_12_ as found in 6.1.12.  Used in 6.12.10 and 6.9.10.
3. _initialized_ as found in  6.1.12, 6.7.15 and 6.8.11 
4. _non-initialized_ as found in 6.4.12, 6.7.15,  6.8.11, 6.12.18, 6.12.10

When testing for erasure (this logic was reversed leading to this bug report):
* if verifying for erasure, only the test results from the _initialized_ list are checked.
* if verifying for no erasure, only the tests results from the _non-initialized_ list are checked.

**Comment by anthonyhbest** [comment]
PACCAR also encountered this issue.
