### ISSUE TITLE
Add the option to use a different source address

### ISSUE THREAD

**Issue by johnyager** [Equipment-and-Tool-Institute/j1939-84#1351]
It would be very helpful for development work to have the ability to run an -84 test using an alternate source address, such as 0xFA. Perhaps a dropdown could be added to the tool's interface, allowing you to choose between running the test as 0xF9 or 0xFA?

**Comment by johnyager** [comment]
As an update, a colleague and I tinkered around with the source code, and made a version that allows you to choose any source address to run the -84 test as.

**Comment by ericthomasswenson** [comment]
Whereas CARB expects the generic tool address of F9h to be used for J1939-84 (since 2011), J3162 [IUMPR], and now Clean Truck Check. This request cannot be considered for C3 umbrella maintenance. Indeed, the performance demonstrated in Part 2 (KOER) is a predictor of success for IUMPR, and Clean Truck Check (HD IM). 

If use of FAh assists in failure isolation during vehicle development tests, this group won’t require the use of F9h for this use case. 

CARB will continue to require 13 CCR 1971.1 (l)(1) and (l)(2) data to be collected using SA F9h. (In my personal opinion) Indeed use of FAh was considered with CARB c. 2012 and was declined.
