### ISSUE TITLE
Part 1 Step 10 should tolerate ACKs

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#568]
```
Start Step 1.10. DM11: Diagnostic Data Clear/Reset for Active DTCs
 
10:08:51.4984 Clearing Diagnostic Trouble Codes
10:08:51.4984 Global DM11 Request
10:08:51.5045 18EAFFF9 [3] D3 FE 00 (TX)
10:08:52.0980 Error: Timeout - No Response.
ERROR: Clearing Diagnostic Trouble Codes failed.
// ACK is to be tolerated, but no specific response is required

6.1.10 DM11: Diagnostic Data Clear/Reset for Active DTCs 
6.1.10.1 Actions: 
a. Global DM11 (send Request (PGN 59904) for PGN 65235).   
b. Record all ACK/NACK/BUSY/Access Denied responses (for PGN 65235) in the log.  
c. Allow 5 s to elapse before proceeding with test step 6.1.9.2. 
6.1.10.2 Fail criteria: 
a. Fail if NACK received from any HD OBD ECU.   
b. Fail if any diagnostic information in any ECU i // b. Is deleted.
```

**Comment by battjt** [comment]
In addition, 6.1.10.1.c is missing.

**Comment by gumbelmj** [comment]
@battjt I've created issue #593 to address the missing 6.1.10.1.c

**Comment by ericthomasswenson** [comment]
The special condition for the 5 s wait for a potential ACK for successful completion will be considered an enhancement.
It would be preferred if the exception for no Global query response, and presumption of successful completion, could be granted for DM11 as that was the expected vehicle performance in 2010-2013.

Footnote 16 says:
_[16] Some ECUs support DM11 by fulfilling or denying the command, then ACKing or NACKing the globally requested operation, because DM11 permanently alters ECU memory values._   

_6.1.10 DM11: Diagnostic Data Clear/Reset for Active DTCs 
6.1.10.1 Actions: 
a. Global DM11 (send Request (PGN 59904) for PGN 65235).   
b. Record all ACK/NACK/BUSY/Access Denied responses (for PGN 65235) in the log.  
c. Allow 5 s to elapse before proceeding with test step 6.1.9.2. 
6.1.10.2 Fail criteria: 
a. **Pass if no response to the global DM11 query has been received in 5 s.**
b. Fail if NACK received from any HD OBD ECU.
6.1.10.3 Warn criteria: a. Warn if ACK received from any HD OBD ECU. [16]_   

// this version of 6.1.10.2.b. Shall be deleted ... as was previously discussed.
b. Fail if any diagnostic information in any ECU ...

**Comment by gumbelmj** [comment]
I think in this case, Step 6.1.10.1.a needs to note that the tool must monitor the bus for five seconds.  (Typically, we only wait 1.2 seconds for responses to global requests.)  Additionally, step "6.1.10.1.c Allow 5 s..." would no longer be required.  We aren't going to check for erased diagnostic information.  The tool will naturally pause here for five seconds while listening for responses.

Further, adding criteria "6.1.10.2.a Pass if no...", doesn't need to be there, nor does step "6.1.10.1.b Record all...".  In no other test do we enumerate the conditions under which the test passes.  Also why does the test need to call out that the responses are logged here, but not anywhere else?  It's my presumption that recording _all_ requests and responses was a fundamental requirement.

**Comment by ericthomasswenson** [comment]
Pass if no response is unusual compared to the rest of the J1939 DM queries... where no response is usually a failure. But it need not be included in fail criteria. Since PG 65235 has no assigned SPs, and since the text is preexisting, I’m inclined to keep d. And add a footnote to that effect.  Also, change warn to info for ACK from OBD ECU.

6.1.10 DM11: Diagnostic Data Clear/Reset for Active DTCs
6.1.10.1 Actions:
a. Global DM11 (send Request (PG 59904) for PGN 65235).
b. Allow 5 s to elapse before proceeding with test step 6.1.9.2. 
**_c. Pass if no response to the global DM11 query has been received in 5 s._**
d. Record all ACK/NACK/BUSY/Access Denied responses (for PG 65235) **from both OBD and Non-OBD ECUs** in the log. **_[XX]_**
6.1.10.2 Fail criteria:
a. Fail if NACK received from any OBD ECU.
6.1.10.3 Warn criteria: 
a. Info: if ACK received from any OBD ECU. 

**_[XX] Only the Acknowledgment PG can be sent in replies, since DM11 is a command assignment with no SPs defined to send in the CAN frame data segment.  DM3 works the same way._**

**Comment by gumbelmj** [comment]
I thought the entire purpose of this particular change was to tolerate ACKs when making a DM11 request.   Step "6.1.10.3.a Warn if ACK received..." should also be removed:

>6.1.10 DM11: Diagnostic Data Clear/Reset for Active DTCs
6.1.10.1 Actions:
a. Global DM11 (send Request (PG 59904) for PGN 65235)
_b. Receive responses for five seconds_
~~c. Pass if no response to the global DM11 query has been received in 5 s.~~
~~d. Record all ACK/NACK/BUSY/Access Denied responses (for PG 65235) from both OBD and Non-OBD ECUs in the log.~~
6.1.10.2 Fail criteria:
a. Fail if NACK received from any HD OBD ECU.
~~6.1.10.3 Warn criteria:
a. Warn if ACK received from any HD OBD ECU.
b. Fail if any diagnostic information in any ECU~~


Recording requests and responses is a fundamental requirements, the exception here (compare with the other steps), is that the tools needs to listen for responses for five seconds. 

(BTW, is there a difference between an "HD OBD ECU" and an "OBD ECU"?  I think the specification should be consistent about the nomenclature.)

**Comment by gumbelmj** [comment]
Response from @ericthomasswenson  via email:

The current performance is:

Part 1 Test 10 [Global DM11 (request 59904 for PGN 65235)]

    0528.190 678	07	 18 EA FF F9 D3 FE 00 (Tx)
    0528.191 067	12	 18 E8 FF 17 00 FF FF FF F9 D3 FE 00 
    0528.194 660	12	 18 E8 FF 00 00 FF FF FF F9 D3 FE 00 
    FAIL: Global DM11 from SA 0 responded with a ACK
    0528.194 948	12	 18 E8 FF ED 00 FF FF FF FD D3 FE 00 
    0528.202 668	12	 18 E8 FF EC 00 FF FF FF FD D3 FE 00 

Part 1 Test 10 [Get Diag Info From ECUs]

Warn is therefore an improvement... from the current circumstances of a false failure.
Let’s split the difference:

6.1.10 DM11: Diagnostic Data Clear/Reset for Active DTCs

6.1.10.1 Actions:

  a. Global DM11 (send Request (PG 59904) for PGN 65235).

b. Allow 5 s to elapse before proceeding with test step 6.1.9.2.

c. Pass if no response to the global DM11 query has been received in 5 s.

d. Record all ACK/NACK/BUSY/Access Denied responses (for PG 65235) from both OBD and Non-OBD ECUs in the log. [XX]

6.1.10.2 Fail criteria:

  a. Fail if NACK received from any HD OBD ECU.

6.1.10.3 Warn criteria

   a. Info: if ACK received from any HD OBD ECU.

[XX] Only the Acknowledgment PG can be sent in replies, since DM11 is a command assignment with no SPs defined to send in the CAN frame data segment. DM3 works the same way.

Also, we should harmonize the following two excerpts: 6.9.8.6.c is the most concise, and likely the clearest.  I believe the two excerpts are equivalent as d is redundant to c in 6.12.9.4.

6.9.8.6 Fail/Warn Criteria3 
a. Fail if any OBD ECU provides a NACK to the global DM11 request.  
b. Info: if any OBD ECU provides an ACK to the global DM11 request.  
c. Fail if any diagnostic information was not erased from any OBD ECUs. 

And,

6.12.9.4 Fail Criteria 
a. Fail if any OBD ECU responds with a NACK. 
b. Info: if any OBD ECU responds with an ACK.  
c. Check diagnostic information and fail if any ECU partially erases diagnostic information (pass if it erases either all or none). 
d. Fail if one OBD ECU or more than one OBD ECU erases diagnostic information and one or more other ECUs do not erase diagnostic information. See Section A.5 for the methods to check for erasure of diagnostic information.

**Comment by gumbelmj** [comment]
@ericthomasswenson, I can agree with this the updates to Test 1.10 and concur that Test 9.6 and 12.9 should be updated as well.

**Comment by ericthomasswenson** [comment]
We agree to harmonize 6.9.8.6 and 6.12.9.4 as:

6.9.8.6 Fail/Warn Criteria3
a. Fail if any OBD ECU provides a NACK to the global DM11 request.
b. **_Info:_** if any OBD ECU provides an ACK to the global DM11 request.
c. Fail if any diagnostic information was not erased from any OBD ECUs.

6.12.9.4 Fail Criteria
a. Fail if any OBD ECU provides a NACK **_to the global DM11 request._**
b. **_Info:_** if any OBD ECU provides an ACK **_to the global DM11 request._**
c. Fail if any diagnostic information was not erased from any OBD ECUs.

**Comment by ericthomasswenson** [comment]
Implemented as described in 17 March 2021 as built draft

**Comment by gumbelmj** [comment]
This needs split.
