### ISSUE TITLE
Questions on Part 9 Step 10

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#682]
Dear @ericthomasswenson, 

The requirements for Part 9 Step 10:
>6.9.10.1.a. DS DM7 with TID 250 and each SPN+FMI from list in part 1 to the OBD ECU that supports the SPN and FMI with test results.
...
6.9.10.2.b. Fail if any difference in what ECU+SPN+FMI combinations have test results compared to the combinations identified in part 1 as having test results.

If I'm understanding this correctly, the tool should issue a DS DM7 for each Supported SPN (from DM24) which indicates it supports Test Results.  However, there is no FMI associated with those SPNs. So for 6.9.10.1.a, what value should be FMI be in the DM7? Should the TID be 247 with FMI 31?

For 6.9.10.2.b, I'm assuming the test results gathered here are to be compared with the test results from Part 1 Step 12.  Is that correct?

**Comment by ericthomasswenson** [comment]
For TID 250, a specific FMI is to be used instead of the generic FMI, 31.  The FMIs disclosed in Part 1 should be iterated for each SPN.  The notes for TID in SAE J1939-73 5.7.7 make this clear.

_TID NOTES:
(1) Test Identifier 247 shall return all the test results for the SPN given in 5.7.7.2. An FMI value of 31 shall be used in 5.7.7.3 by scan tools to query for test results with TID 247. With the FMI value of 31 is used, the test results provided shall comprise all test results for the SPN given in 5.7.7.2 regardless of their assigned FMIs including FMI 31. When there is no information regarding what specific FMIs are supported, the individual SPNs, indicated by DM24 as having test results, may therefore be queried using Test Identifier 247, the SPN displayed, and FMI 31._

_**Test Identifier 250** is used when the results for **only one test** is desired where the test is defined by the SPN given in 5.7.7.2 and the FMI given in 5.7.7.3._

_(2) SPN 4175 (Diesel Particulate Filter Active Regeneration Forced Status) with an FMI of 31 shall be used with TID 249 to provide a common means for scan-tool user requests to regenerate a DPF PM aftertreatment system. This capability is not required for OBD compliance._

_(3) TID 246 - SPN 5846 (OBD test results) with an FMI of 31 shall be used with TID 246 to provide a common means for scan-tool user request for all test results. This method of request could require more than 200 bytes to report all results for all OBD test results. This capability is not required for OBD compliance._

Should it be the case that TID 250 is not supported, then TID 247 with the generic FMI is used, in the current SourceForge software. Unfortunately the text does not say that.  [And presumes specific knowledge of DM7 and the TID table values].

Since DM11 was issued in the previous step, there is no prior result standard for comparison as the expectation is that all test results were initialized (in this test).  Indeed the failure criteria, directs any results that are not initialized (FB00h/FFFFh/FFFFh or 0000h/0000h/0000h) should be identified as failures.  Note that multiple test results for an individual FMI (where the SPN is repeated in each result) will be received as they were received for TID 247 in part 1. 

BTW, the TID for DM58 is TID 245.

**Comment by ericthomasswenson** [comment]
The following suggestions are recommended in the March 10 draft to match the existing software.

6.9.10.1	Actions
a.	_Iterate a_ DS DM7 request with TID 250 _for each (unique)_ SPN+FMI from the SPN+FMI list received in part 1 to the _OBD ECU that supports the SPN with test results in its DM24 response._ 
_b.	If the response for the TID 250 query is NACK (control byte = 1), then send DS DM7, for the SP using TID 247 and FMI 31 to obtain all test results for the SPN.  [Item b. will be performed commonly for all SPs where TID 250 is not supported by the OBD ECU.]_
6.9.10.2	Fail Criteria
a.	Fail if any test result _received is_ not initialized. _[I.E. does not display FB00h/FFFFh/FFFFh or 0000h/0000h/0000h]._
b.	Fail if any difference in what ECU+SPN+FMI combinations have test results compared to the combinations identified in part 1 as having test results.
_c.	Fail each SP exercised, where there is no response for TID 250 and TID 247 queries._

**Comment by ericthomasswenson** [comment]
Implementation in the March 10 draft affirmed during March 17 as built draft proposal implementation.
