### ISSUE TITLE
Ignition Cycle Failure in Part 7

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/j1939-84#760]
@ericthomasswenson ,

I'm trying to fix our Simulated Engine to pass this test without any failures.  I have an ignitionCycle counter which I increment by one when the engine goes from not running to running.

In Part 6, we find this requirement:
> 6.6.11.1.d If required by engine manufacturer, start the engine to start operating cycle effects.

If the engine is not started at this point, then the test fails in Part 7:

>6.7.13.2.a. Fail if ignition cycle counter (SPN 3048) for any ECU has incremented by other than 3 cycles from part 5.

Am I mis-understanding what an ignition cycle is?

**Comment by ericthomasswenson** [comment]
6.6.11 Complete Fault A Three Trip Countdown Cycle 3 
6.6.11.1 Actions 
a. Turn engine off. 
b. Wait engine manufacturer’s recommended interval.  
c. Turn key to on position.  
d. If required by engine manufacturer, start the engine for start to start operating cycle effects.  
e. Otherwise, Proceed with part 7.  
f. Turn engine off.  
g. Wait engine manufacturer’s recommended interval.  
h. Turn the key to the on position.  
i. Proceed with part 7.

**Comment by ericthomasswenson** [comment]
[Countdown-cycle-transition-instruction-review.docx](https://github.com/battjt/j1939-84/files/6143820/Countdown-cycle-transition-instruction-review.docx)
Inspecting Figure 2, One May conclude that Cycle 6b is not optional, as a three cycle countdown is a key requirement in 13 CCR 1971.1. No manufacturer should direct the omission of cycle 6b. They may omit 8b, for one trip faults used as Fault B. But the optional engine start, is not intended to provide cycle 6b.

The “start-to-start” operating cycle definition (below) adds complexity to meeting the regulation. The extra cycle is a hedge for CARB “start-to-start” operating cycle definition... and **_after at least three subsequent sequential driving cycles_**.  If the MIL is not extinguished until the start of 4th driving cycle (which is the end of the 3rd operating cycle), an engine start is required to accomplish the DM12 to DM23 transition. The engine manufacturer must tell users when this is the case.

Retain _If required by engine manufacturer,_  from d. above and footnote the circumstances.  Clarify the waiting time purposes.

6.6.11 Complete Fault A Three Trip Countdown Cycle 3 
6.6.11.1 Actions 
a. Turn engine off. 
b. Wait engine manufacturer’s recommended interval, **_for key off transition._**
c. Turn key to on position.  
d. If required by engine manufacturer, start the engine for start to start operating cycle effects.  _**[xx]**_
e. Otherwise, Proceed with part 7.  
f. Turn engine off.  
g. Wait engine manufacturer’s recommended interval, **_for key off transition_** 
h. Turn the key to the on position.  
i. Proceed with part 7.  

**_[xx] Manufacturers shall disclose those implementations which require an engine start to recognize  the end of the third operating cycle before they extinguish the MIL, delete the DM12 MIL-on fault, and display the DM23 previous MIL-on fault._**

**Comment by gumbelmj** [comment]
I think Point 'e' needs changed:

6.6.11 Complete Fault A Three Trip Countdown Cycle 3
6.6.11.1 Actions
a. Turn engine off.
b. Wait engine manufacturer’s recommended interval.
c. Turn key to on position.
d. Start the engine ~~for start~~ to start operating cycle effects.
_e. Wait engine manufacturer’s recommended interval._
f. Turn engine off.
g. Wait engine manufacturer’s recommended interval.
h. Turn the key to the on position.
i. Proceed with part 7.

Further more we may wish to consolidate "turn engine on" with "start engine".  In our software they are two different steps, which require input from the user.

**Comment by ericthomasswenson** [comment]
From 13 CCR 1971.1
_(c) “Driving cycle” is defined as a trip that meets any of the four conditions below:
 (1) Begins with engine start and ends with engine shutoff;
 (2) Begins with engine start and ends after four hours of continuous engine-on
operation;
 (3) Begins at the end of the previous four hours of continuous engine-on
operation and ends after four hours of continuous engine-on operation; or
 (4) Begins at the end of the previous four hours of continuous engine-on
operation and ends with engine shutoff._

**Comment by ericthomasswenson** [comment]
From 13 CCR 1971.1,
(d)(2.3.2) For vehicles using the SAE J1939 protocol for the standardized functions required in section (h):
(A) Extinguishing the MIL. Except as otherwise provided in sections (e)(1.4.2)(F), (e)(2.4.2)(D) and (e)(6.4.2) for fuel system malfunctions, misfire malfunctions, and empty reductant tanks, once the MIL has been
illuminated, **_it shall be extinguished after at least three subsequent sequential driving cycles during which the monitoring system responsible for illuminating the MIL functions and the previously detected malfunction is no longer present_** provided no other malfunction has been detected that would independently illuminate the MIL according to the requirements outlined above.
(B) Erasing a MIL-on fault code. The OBD system may _[shall]_ **_erase a MIL-on fault code in conjunction with extinguishing the MIL as described under section (d)(2.3.2)(A). In addition to the erasure of the MIL-on fault code, the OBD system shall store a previously MIL-on fault code for that failure._**
(C) Erasing a previously MIL-on fault code. For 2010 through 2015 model year engines, the OBD system may erase a previously MIL-on fault code if the identified malfunction has not been again detected in at least 40 engine warm-up cycles and the MIL is presently not illuminated for that malfunction. For 2016 and subsequent model year engines, the OBD system shall erase a previously MIL-on fault code if the identified malfunction has not been again detected in 40 warm-up cycles and the MIL is presently not illuminated for that malfunction. _[The 40 cycle provision is not tested]_
(D) Erasing a permanent fault code. The OBD system shall erase a permanent fault code under the following conditions:
(i) If the OBD system is commanding the MIL on, the OBD system shall
erase a permanent fault code only if the OBD system itself determines that the malfunction that caused the permanent fault code to be stored is no longer present and is not commanding the MIL on, pursuant to the requirements of section (d)(2.3.2)(A) (which for the purposes of this section shall apply to all monitors). **_Erasure of the permanent fault code shall occur in conjunction with extinguishing the MIL or no later than the start of the first drive cycle that begins with the MIL commanded off._**
(ii) If all fault information in the on-board computer has been cleared (i.e., through the use of a scan tool or battery disconnect) and the OBD system is not commanding the MIL on:
a. Except as provided for in section (d)(2.3.2)(D)(ii)c., if the monitor of
the malfunction that caused the permanent fault code to be stored is subject to the minimum ratio requirements of section (d)(3.2) (e.g., catalyst monitor, comprehensive component input component rationality monitors), **_the OBD system shall erase the permanent fault code at the end of a driving cycle if the monitor has run and made one or more determinations during a driving cycle that the malfunction of the component or the system is not present and has not made any determinations within the same driving cycle that the malfunction is present._**
b. If the monitor of the malfunction that caused the permanent fault code to be stored is not subject to the minimum ratio requirements of section (d)(3.2) (e.g., continuous diesel fuel system monitors, comprehensive component circuit continuity monitors), the OBD system shall erase the permanent fault code at the end of a driving cycle if:
1. The monitor has run and made one or more determinations during a driving cycle that the malfunction of the component or the system is not present and has not made any determinations within the same driving cycle that the malfunction is present;
2. The monitor has not made any determinations that the malfunction is present subsequent to the most recent driving cycle in which the criteria of section (d)(2.3.2)(D)(ii)b.1. are met; and
3. The following criteria are satisfied on any single driving cycle (which may be a different driving cycle than that in which the criteria of section (d)(2.3.2)(D)(ii)b.1. are satisfied):
i. Except as provided in section (d)(2.3.2)(D)(ii)b.3.v. below,
Ccumulative time since engine start is greater than or equal
to 600 seconds;
ii. Cumulative gasoline engine operation at or above 25 miles
per hour or diesel engine operation at or above 1150 rpm, either of which occurs for greater than or equal to 300 seconds;
iii. Continuous vehicle operation at idle (i.e., accelerator pedal released by driver and either vehicle speed less than or equal to one mile per hour or engine speed less than or equal to 200 rpm above normal warmed-up idle (as determined in the drive position for vehicles equipped with an automatic transmission)) for greater than or equal to 30 seconds; and
iv. The monitor has not made any determinations that the malfunction is present.
v. For hybrid vehicles, manufacturers shall use “cumulative propulsion system active time” in lieu of “cumulative time since engine start” for the criterion in section (d)(2.3.2)(D)(ii)b.3.i.
4. Monitors required to use “similar conditions” as defined in section (c) to store and erase pending and confirmed/MIL-on fault codes may not require that the similar conditions be met prior to erasure of the permanent fault code.
c. For monitors subject to section (d)(2.3.2)(D)(ii)a., the manufacturer may choose to erase the permanent fault code using the criteria under section (d)(2.3.2)(D)(ii)b. in lieu of the criteria under section (d)(2.3.2)(D)(ii)a.

**Comment by ericthomasswenson** [comment]
Text implemented in 17 March 2021 as-built draft
