### ISSUE TITLE
Test not Complete is Not Initialized?

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/j1939-84#850]
This juxtaposition just looks like a fallacy, but the SPNs are different 

10:55:40.9287 Sending DM7 for DM30 to DPF Controller (85) for SPN 7393
10:55:40.9341 18E355F9 [8] FA E1 1C 01 FF FF FF FF (TX)
10:55:40.9436 18A4F955 [12] FA E1 1C 01 20 00 00 FB FF FF FF FF
DM30 from 85: SPN **_7393_** FMI 1 (SLOT 32) Result: Test Not Complete.
FAIL: 6.9.10.2.a - DPF Controller (85) reported test result for SPN = **_7330_**, FMI = 2 is not initialized

End Test 9.10 - DM7/DM30: Command non-continuously monitored test/scaled test results

**Comment by gumbelmj** [comment]
In order to make the code easy to inspect, troubleshoot and update, it's designed to mirror the specification.  In nearly all cases, we perform the first step before moving onto other ones.

Thus the first step here is 
> 6.9.10.1.a. DS DM7 with TID 250 and each SPN+FMI from list in part 1 to the OBD ECU that supports the SPN and FMI with test results.

Once we have requested all the test results, we inspect them per:
> 6.9.10.2.a. Fail if any test result not initialized.

See the code in [Part9Step10Controller](https://github.com/battjt/j1939-84/blob/f6929be97ab116c90b16683f74324db48450d9d2/src/org/etools/j1939_84/controllers/part09/Part09Step10Controller.java#L63-L64)

**Comment by ericthomasswenson** [comment]
So as a part of the white space work let’s add a line

10:55:40.9287 Sending DM7 for DM30 to DPF Controller (85) for SPN 7393
10:55:40.9341 18E355F9 [8] FA E1 1C 01 FF FF FF FF (TX)
10:55:40.9436 18A4F955 [12] FA E1 1C 01 20 00 00 FB FF FF FF FF
DM30 from 85: SPN 7393 FMI 1 (SLOT 32) Result: Test Not Complete.
            <Modeled blank line here>
FAIL: 6.9.10.2.a - DPF Controller (85) reported test result for SPN = 7330, FMI = 2 is not initialized
...

_**and also say:**_
**_6.9.10.2.a - No test results failed_**

End Test 9.10 - DM7/DM30: Command non-continuously monitored test/scaled test results

**Comment by ericthomasswenson** [comment]
Need strategy for KOEO tests … as KOEO tests are a known weakness of CARBs guidance for test results outcomes.

**Comment by ericthomasswenson** [comment]
Recent work for tests that never run and tests that run KOEO supersede this report.

See #1130, #1039
