### ISSUE TITLE
Incorrect FAIL assessment on DM26 - SPN 3301, 3302, 3303, 3304 and 3305

### ISSUE THREAD

**Issue by vmuthu2** [Equipment-and-Tool-Institute/j1939-84#996]
New issue introduced with v 3.0.8.. Issue was not present in v3.0.7

DM26 reports correctly and all the SPNs are supported as expected.

15:22:52.2934 DS Request for PGN 64952 to Engine #1 (0) for SPNs 3301, 3302, 3303, 3304, 3305
15:22:52.2972 18EA00F9 [3] B8 FD 00 (TX)
15:22:52.3002 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
PGN 64952 with Supported SPNs 3301, 3302, 3303, 3304, 3305
15:22:52.3002 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
Found: DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
FAIL: 6.1.26.6.a - SPN 3301 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3302 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3303 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3304 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3305 was received as NOT AVAILABLE from Engine #1 (0)

15:24:44.2727 DS Request for PGN 64952 to Engine #1 (0) for SPNs 3301, 3302, 3303, 3304, 3305
15:24:44.2763 18EA00F9 [3] B8 FD 00 (TX)
15:24:44.2785 18FDB800 [8] 65 00 00 37 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 101 seconds
PGN 64952 with Supported SPNs 3301, 3302, 3303, 3304, 3305
15:24:44.2785 18FDB800 [8] 65 00 00 37 E0 1E E0 1E
Found: DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 101 seconds
FAIL: 6.2.17.6.a - SPN 3301 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3302 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3303 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3304 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.2.17.6.a - SPN 3305 was received as NOT AVAILABLE from Engine #1 (0)

**Comment by ericthomasswenson** [comment]
14:04:47.7660 DS Request for PGN 64952 to Engine #1 (0) for SPNs 3301, 3302, 3303
14:04:47.7705 18EA00F9 [3] B8 FD 00 (TX)
14:04:47.7741 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
PGN 64952 with Supported SPNs 3301, 3302, 3303
14:04:47.7741 18FDB800 [8] 00 00 00 37 E0 1E E0 1E
Found: DM26 from Engine #1 (0): Warm-ups: 0, Time Since Engine Start: 0 seconds
FAIL: 6.1.26.6.a - SPN 3301 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3302 was received as NOT AVAILABLE from Engine #1 (0)

FAIL: 6.1.26.6.a - SPN 3303 was received as NOT AVAILABLE from Engine #1 (0)
